import Head from 'next/head'
import Image from 'next/image'

export default function Home () {
 
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='stylesheet'
          href='https://cdn.jsdelivr.net/npm/animate.css@3.5.2/animate.min.css'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className=''>
       Ade is cool my boy dd
      </main>

      <footer className=''>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className=''>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
